#!/usr/bin/env python

"""Amulet tests on a basic manila deployment on xenial-mitaka.
"""

from basic_deployment import ManilaBasicDeployment

if __name__ == '__main__':
    # TODO: disable the gate test to land the charm. - remove once
    # manila-generic is landed
    pass
    # deployment = ManilaBasicDeployment(series='xenial')
    # deployment.run_tests()
