options:
  openstack-origin:
    default: distro
    type: string
    description: |
      Repository from which to install.  May be one of the following:
      distro (default), ppa:somecustom/ppa, a deb url sources entry,
      or a supported Cloud Archive release pocket.

      Supported Cloud Archive sources include: cloud:precise-folsom,
      cloud:precise-folsom/updates, cloud:precise-folsom/staging,
      cloud:precise-folsom/proposed.

      Note that updating this setting to a source that is known to
      provide a later version of OpenStack will trigger a software
      upgrade.
  rabbit-user:
    default: manila
    type: string
    description: Username used to access rabbitmq queue
  rabbit-vhost:
    default: openstack
    type: string
    description: Rabbitmq vhost
  database-user:
    default: manila
    type: string
    description: Username for Manila database access
  database:
    default: manila
    type: string
    description: Database name for Manila
  debug:
    default: False
    type: boolean
    description: Enable debug logging
  verbose:
    default: False
    type: boolean
    description: Enable verbose logging
  region:
    default: RegionOne
    type: string
    description: OpenStack Region
  share-backends:
    type: string
    description: |
      A space delimited list of the backends this manila set should expose.
      If no backends are specified then the charm will block.
      The current selection is - generic
  share-protocols:
    type: string
    default: NFS CIFS
    description: |
      The share protocols that the backends will be able to provide.  The
      default is good for the generic backends.  Other backends may not support
      both NFS and CIFS.  This is a space delimited list of protocols.
  default-share-backend:
    type: string
    description: |
      The default backend for this manila set. Must be one of the
      'share-backends' or the charm will block.
  default-share-type:
    type: string
    default: default_share_type
    description: |
      The 'default_share_type' must match the the configured default_share_type
      set up in manila using 'manila create-type'.
  generic-driver-service-image-name:
    type: string
    description: the image name to use for the generic instance
    default: manila-service-image
  generic-driver-handles-share-servers:
    type: boolean
    description: Whether to generic driver should run up a share server.
    default: True
  generic-driver-service-instance-flavor-id:
    type: int
    description: |
      The ID for the flavor to launch images in. The driver blocks if this is
      not set.
  generic-driver-connect-share-server-to-tenant-network:
    type: boolean
    default: True
    description: Whether to connect the share server into the tenant network.
  generic-driver-service-instance-user:
    type: string
    description: The user to log into the share instance.
    default: manila
  generic-driver-auth-type:
    type: string
    description: |
      One of 'password', 'ssh', 'both'.  This determines how manila
      authenticates against the service-instance; e.g. using password, ssh
      keypair or both.
  generic-driver-service-instance-password:
    type: string
    description: |
      If the service user doesn't log in with a key-pair a password is needed
      to allow manila to ssh into the service instance.  If the password is set
      then it is used and an SSH key is not configured.
  generic-driver-service-ssh-key:
    type: string
    description: |
      The key for the manila to inject into the instance.  If set, manila will
      inject it into OpenStack if the keypair name doesn't exist.
  generic-driver-service-ssh-key-public:
    type: string
    description: |
      The public key for the manila to inject into the instance.  If set,
      manila will inject it into OpenStack if the keypair name doesn't exist.
  generic-driver-keypair-name:
    type: string
    default: manila-service
    description: |
      This is the keypair name that will be provided to nova instances.  Note
      that manila uploads the keypair from the config settings
      'generic-driver-ssh-private-key' and 'generic-driver-ssh-public-key'.  If
      neither the ssh config vars are set nor the password then the charm will
      block until they are set.
